#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run lint-staged to check and fix staged files
npx lint-staged

# Type check the entire project
npm run type-check

# Run linting on the entire project
npm run lint
